#+title: Chapter 1
:settings:
#+options: num:nil toc:nil ^:nil
#+HTML_HEAD: <link rel="stylesheet" href="../css/tufte.css" type="text/css" />
#+CSL_STYLE: ../style.csl
:end:


* Section headings

Enjoy org-style sections headings.

Lists also work:

- Fusce sagittis, libero non molestie mollis, magna orci ultrices dolor, at vulputate neque nulla lacinia eros.   
- Praesent fermentum tempor tellus.
- Aliquam posuere. 

Anything in top-level sections will be exported in a regular, book-style
formatting. Anything smaller than a top-level section will appear as a
bulletpointed list, useful for outlining books-in-progress:

** TODO Heading 2

*** Heading 3

**** Heading 4

***** TODO Heading 5

You can include text in these outlines.

***** DONE Heading 5
CLOSED: [2021-07-17 Sat 14:57]

Marking things done is also great.

**** Heading 4

***** Heading 5

Etiam vel neque nec dui dignissim bibendum.  

****** Heading 6

******* DONE Heading 7
CLOSED: [2021-07-17 Sat 14:57]
Vestibulum convallis, lorem a tempus semper, dui dui euismod elit, vitae placerat urna tortor vitae lacus.  
******* TODO Heading 7

Donec vitae dolor. Curabitur lacinia pulvinar nibh.   
* Margin notes

Footnotes become margin notes. [fn:1] 

* Epigraph

#+begin_quote
This will become an epigraph.
#+end_quote

* TODO References

References should also appear on the margins cite:nietzsche. The citation will
also appear in the "Biliography" section at the end of the document.

Repeated references should be shortened cite:nietzsche,hegel. 

* WAIT Images

Figures can have captions. 

# TODO - figure with caption and label.

You can reference figures (Figure *XXX*).

Figures and images can also go in the margin.[fn:2] 
* Footnotes
[fn:2] TODO figure in the margin

[fn:1] This is a numbered margin note. Unnumbered margin notes are also
supported with the somewhat cumbersome syntax =[[mn:1][My unnumbered margin
note.]]=. This syntax isn't very "org-y" to me, but I see the appeal of not
having a number.


bibliography:../references.bib
